# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: mercari-search-batch

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0,5,10,15,20,25,30,35,40,45,50,55, * * * *'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set envs
      run: |
           touch .env          
           echo "ACCESS_TOKEN_KEY=\"${{ secrets.ACCESS_TOKEN_KEY }}\"" >> .env
           echo "ACCESS_TOKEN_SECRET=\"${{ secrets.ACCESS_TOKEN_SECRET }}\"" >> .env
           echo "CONSUMER_KEY=\"${{ secrets.CONSUMER_KEY }}\"" >> .env
           echo "CONSUMER_SECRET=\"${{ secrets.CONSUMER_SECRET }}\"" >> .env
    - name: exec
      run: python ./mercariSearch.py "${{secrets.SEARCH_STRING}}"
